import { StyleSheet } from "react-native";
import { RFValue } from "react-native-responsive-fontsize";
import { Theme } from "../../../../contexts/ThemeContext";
import { getMacroPillColors } from "../../utils/macroColors";

export const createProductSearchStyles = (theme: Theme, isDark: boolean) => {
  const kcal = getMacroPillColors("calories", isDark);
  const protein = getMacroPillColors("protein", isDark);
  const carbs = getMacroPillColors("carbs", isDark);
  const fat = getMacroPillColors("fat", isDark);

  return StyleSheet.create({
    headerBlock: {
      paddingHorizontal: 20,
      paddingTop: 8,
      paddingBottom: 12,
      backgroundColor: theme.backgroundSecondary,
      borderBottomWidth: 1,
      borderBottomColor: theme.border,
    },
    headerRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: 12,
      marginBottom: 4,
    },
    backButton: {
      width: 44,
      height: 44,
      borderRadius: 22,
      backgroundColor: theme.card,
      justifyContent: "center",
      alignItems: "center",
      borderWidth: 1,
      borderColor: theme.border,
    },
    headerTextBlock: {
      flex: 1,
    },
    headerTitle: {
      fontSize: RFValue(20),
      fontWeight: "800",
      color: theme.text,
      letterSpacing: -0.3,
    },
    headerSubtitle: {
      fontSize: RFValue(12),
      color: theme.textSecondary,
      marginTop: 2,
      fontWeight: "500",
    },
    searchSection: {
      paddingHorizontal: 20,
      paddingTop: 14,
      paddingBottom: 12,
      backgroundColor: theme.backgroundSecondary,
      gap: 10,
    },
    searchBarOuter: {
      flexDirection: "row",
      alignItems: "center",
      backgroundColor: theme.card,
      borderRadius: 16,
      paddingHorizontal: 14,
      minHeight: 52,
      borderWidth: 1.5,
      borderColor: theme.inputBorder,
      shadowColor: theme.shadowColor,
      shadowOpacity: isDark ? 0 : 0.06,
      shadowRadius: 12,
      shadowOffset: { width: 0, height: 4 },
      elevation: isDark ? 0 : 2,
    },
    searchBarOuterFocused: {
      borderColor: theme.primary,
      shadowOpacity: isDark ? 0 : 0.1,
    },
    searchInput: {
      flex: 1,
      flexShrink: 1,
      minWidth: 0,
      fontSize: RFValue(15),
      color: theme.text,
      paddingVertical: 12,
      marginLeft: 8,
      paddingRight: 4,
    },
    searchIconButton: {
      width: 40,
      height: 40,
      borderRadius: 12,
      justifyContent: "center",
      alignItems: "center",
      flexShrink: 0,
    },
    searchIconButtonActive: {
      backgroundColor: `${theme.primary}18`,
    },
    quickActionsRow: {
      flexDirection: "row",
      gap: 8,
    },
    quickActionChip: {
      flexDirection: "row",
      alignItems: "center",
      gap: 6,
      paddingHorizontal: 12,
      paddingVertical: 8,
      borderRadius: 999,
      backgroundColor: theme.card,
      borderWidth: 1,
      borderColor: theme.border,
    },
    quickActionChipPrimary: {
      backgroundColor: theme.primary,
      borderColor: theme.primary,
    },
    quickActionText: {
      fontSize: RFValue(12),
      fontWeight: "600",
      color: theme.textSecondary,
    },
    quickActionTextPrimary: {
      color: theme.onPrimary,
    },
    activeFiltersScroll: {
      paddingHorizontal: 20,
      paddingBottom: 10,
      backgroundColor: theme.backgroundSecondary,
    },
    activeFiltersContent: {
      flexDirection: "row",
      gap: 8,
      alignItems: "center",
    },
    activeFilterChip: {
      flexDirection: "row",
      alignItems: "center",
      gap: 6,
      paddingLeft: 12,
      paddingRight: 8,
      paddingVertical: 6,
      borderRadius: 999,
      backgroundColor: `${theme.primary}15`,
      borderWidth: 1,
      borderColor: `${theme.primary}40`,
    },
    activeFilterText: {
      fontSize: RFValue(12),
      fontWeight: "600",
      color: theme.primary,
    },
    searchStatusBanner: {
      flexDirection: "row",
      alignItems: "center",
      gap: 10,
      paddingVertical: 12,
      paddingHorizontal: 14,
      marginBottom: 12,
      borderRadius: 12,
      backgroundColor: isDark ? `${theme.primary}20` : `${theme.primary}10`,
      borderWidth: 1,
      borderColor: isDark ? `${theme.primary}35` : `${theme.primary}22`,
    },
    searchStatusText: {
      flex: 1,
      color: theme.text,
      fontSize: RFValue(13),
      fontWeight: "600",
      lineHeight: RFValue(18),
    },
    productCard: {
      flexDirection: "row",
      backgroundColor: theme.card,
      borderRadius: 16,
      padding: 12,
      alignItems: "center",
      marginBottom: 10,
      borderWidth: 1,
      borderColor: theme.border,
      shadowColor: theme.shadowColor,
      shadowOpacity: isDark ? 0 : 0.05,
      shadowRadius: 8,
      shadowOffset: { width: 0, height: 2 },
      elevation: isDark ? 0 : 1,
    },
    productImageWrap: {
      borderRadius: 12,
      backgroundColor: theme.backgroundSecondary,
      justifyContent: "center",
      alignItems: "center",
      overflow: "hidden",
      position: "relative",
    },
    productImage: {
      resizeMode: "contain",
    },
    gradeBadge: {
      position: "absolute",
      top: 4,
      left: 4,
      minWidth: 22,
      height: 22,
      borderRadius: 6,
      justifyContent: "center",
      alignItems: "center",
      paddingHorizontal: 4,
    },
    gradeBadgeText: {
      color: "#fff",
      fontSize: 10,
      fontWeight: "800",
    },
    productBody: {
      flex: 1,
      marginLeft: 12,
      minWidth: 0,
    },
    productName: {
      fontWeight: "700",
      color: theme.text,
      marginBottom: 2,
    },
    productBrand: {
      color: theme.textTertiary,
      fontWeight: "500",
      marginBottom: 8,
    },
    macroRow: {
      flexDirection: "row",
      flexWrap: "wrap",
      gap: 6,
      alignItems: "center",
    },
    macroPill: {
      flexDirection: "row",
      alignItems: "center",
      gap: 4,
      paddingHorizontal: 8,
      paddingVertical: 4,
      borderRadius: 8,
      backgroundColor: theme.backgroundSecondary,
    },
    macroPillKcal: {
      backgroundColor: kcal.background,
    },
    macroPillProtein: {
      backgroundColor: protein.background,
    },
    macroPillCarbs: {
      backgroundColor: carbs.background,
    },
    macroPillFat: {
      backgroundColor: fat.background,
    },
    macroPillText: {
      fontSize: RFValue(10),
      fontWeight: "600",
      color: theme.textSecondary,
    },
    macroPillTextKcal: {
      color: kcal.text,
    },
    macroPillTextProtein: {
      color: protein.text,
    },
    macroPillTextCarbs: {
      color: carbs.text,
    },
    macroPillTextFat: {
      color: fat.text,
    },
    addButton: {
      width: 44,
      height: 44,
      borderRadius: 22,
      backgroundColor: `${theme.primary}18`,
      justifyContent: "center",
      alignItems: "center",
      marginLeft: 8,
    },
    favoriteBadge: {
      position: "absolute",
      bottom: 4,
      right: 4,
      width: 24,
      height: 24,
      borderRadius: 12,
      backgroundColor: theme.card,
      justifyContent: "center",
      alignItems: "center",
      borderWidth: 1,
      borderColor: theme.border,
    },
    emptyContainer: {
      alignItems: "center",
      justifyContent: "center",
      paddingVertical: 48,
      paddingHorizontal: 32,
    },
    emptyIconWrap: {
      width: 88,
      height: 88,
      borderRadius: 44,
      backgroundColor: theme.backgroundSecondary,
      justifyContent: "center",
      alignItems: "center",
      marginBottom: 16,
    },
    emptyTitle: {
      fontSize: RFValue(17),
      fontWeight: "700",
      color: theme.text,
      textAlign: "center",
      marginBottom: 8,
    },
    emptySubtitle: {
      fontSize: RFValue(14),
      color: theme.textSecondary,
      textAlign: "center",
      lineHeight: RFValue(20),
    },
    primaryButton: {
      flexDirection: "row",
      alignItems: "center",
      gap: 8,
      marginTop: 24,
      paddingHorizontal: 20,
      paddingVertical: 14,
      borderRadius: 14,
      backgroundColor: theme.primary,
    },
    primaryButtonText: {
      color: theme.onPrimary,
      fontSize: RFValue(15),
      fontWeight: "700",
    },
    skeletonRoot: {
      flex: 1,
      width: "100%",
      paddingHorizontal: 16,
      paddingTop: 12,
      paddingBottom: 24,
      alignSelf: "stretch",
    },
    skeletonCard: {
      flexDirection: "row",
      alignItems: "center",
      backgroundColor: theme.card,
      borderRadius: 16,
      padding: 12,
      marginBottom: 10,
      borderWidth: 1,
      borderColor: isDark ? theme.border : "#EEF2F7",
    },
    skeletonImage: {
      borderRadius: 12,
      backgroundColor: isDark ? "#2A3647" : "#EEF2F7",
      flexShrink: 0,
    },
    skeletonBody: {
      flex: 1,
      marginLeft: 12,
      minWidth: 0,
      justifyContent: "center",
    },
    skeletonLine: {
      height: 12,
      borderRadius: 6,
      backgroundColor: isDark ? "#2A3647" : "#EEF2F7",
      marginBottom: 8,
    },
    skeletonPillRow: {
      flexDirection: "row",
      flexWrap: "wrap",
      gap: 6,
      alignItems: "center",
    },
    skeletonPill: {
      borderRadius: 8,
      backgroundColor: isDark ? "#2A3647" : "#EEF2F7",
    },
    skeletonTrailing: {
      width: 44,
      height: 44,
      borderRadius: 22,
      marginLeft: 8,
      backgroundColor: isDark ? "#2A3647" : "#EEF2F7",
      flexShrink: 0,
    },
    skeletonMessage: {
      marginTop: 12,
      textAlign: "center",
      fontSize: RFValue(13),
      fontWeight: "600",
      color: theme.textSecondary,
      paddingHorizontal: 16,
    },
  });
};
